### ISSUE TITLE
[JENKINS-72401] The priorities defined in JCasC are not set correctly in Jenkins

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/priority-sorter-plugin#629]
<p><b>Reproduction steps</b></p>

<p>1. Set the following config for priority-sorter</p>

```
priorityConfiguration:
  jobGroups:
    - jobGroupStrategy: "allJobs"
      priority: -1
      priorityStrategies:
- buildParameterStrategy:
    parameterName: "PRIORITY"
- userIdCauseStrategy:
    priority: 4
      usePriorityStrategies: true
prioritySorterConfiguration:
  onlyAdminsMayEditPriorityConfiguration: true
  strategy:
    absoluteStrategy:
      defaultPriority: 5
      numberOfPriorities: 7

```
<p>2. Start Jenkins with the above configuration</p>

<p><b>Observed result</b></p>

<p>The actual value of the userIdCausePriority is 3 as can be shown by extracting the configuration of the plugin from the instance of Jenkins.</p>

```
priorityStrategy:
  userIdCauseStrategy:
    priority: 3

```
<p><b>Expected result</b></p>

<p>The expected value of the userIdCausePriority is 4 as defined in the input configuration file.</p>

```
priorityStrategy:
  userIdCauseStrategy:
    priority: 4

```
<p><b>Root cause</b></p>

<p>The 'scale' method in PriorityCalculationsUtil seems to be called when the JCasC configuration is being applied. The method returns distorted results due to numerical anomalies - apparently the actual float values are a little smaller/bigger than expected ones (e.g. 0.3(9) instead of 0.4) so the used 'floor' and 'ceil' functions may lead to wrong results.</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=cytrek">cytrek</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-72401" target="_blank">The priorities defined in JCasC are not set correctly in Jenkins</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: prioritysorter-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 1
<li><b>watchers</b>: 4
<li><b>imported</b>: 20251211-071809
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p><b>Reproduction steps</b></p>

<p>1. Set the following config for priority-sorter</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>priorityConfiguration:
  jobGroups:
    - jobGroupStrategy: "allJobs"
      priority: -1
      priorityStrategies:
        - buildParameterStrategy:
            parameterName: "PRIORITY"
        - userIdCauseStrategy:
            priority: 4
      usePriorityStrategies: true
prioritySorterConfiguration:
  onlyAdminsMayEditPriorityConfiguration: true
  strategy:
    absoluteStrategy:
      defaultPriority: 5
      numberOfPriorities: 7
</pre>
</div></div>
<p>2. Start Jenkins with the above configuration</p>

<p><b>Observed result</b></p>

<p>The actual value of the userIdCausePriority is 3 as can be shown by extracting the configuration of the plugin from the instance of Jenkins.</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>priorityStrategy:
  userIdCauseStrategy:
    priority: 3
</pre>
</div></div>
<p><b>Expected result</b></p>

<p>The expected value of the userIdCausePriority is 4 as defined in the input configuration file.</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>priorityStrategy:
  userIdCauseStrategy:
    priority: 4
</pre>
</div></div>
<p><b>Root cause</b></p>

<p>The 'scale' method in PriorityCalculationsUtil seems to be called when the JCasC configuration is being applied. The method returns distorted results due to numerical anomalies - apparently the actual float values are a little smaller/bigger than expected ones (e.g. 0.3(9) instead of 0.4) so the used 'floor' and 'ceil' functions may lead to wrong results.</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
jenkins:2.414.3-lts-alpine<br/>
priority-sorter 5.0.0
```
</details>
